networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  db:
    image: postgres:15
    volumes:
        - postgres_data:/var/lib/postgresql/data/
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        - POSTGRES_DB-server
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"

  web:
    build: ./appointment-dashboard
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
    environment:
        - DATABASE_HOST=db
    depends_on:
        - db

  bot:
    build: ./bot-appointment-dashboard
    volumes:
        - ./bot/.env:/app/.env

volumes:
  postgres_data:
